// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.2
// source: proto/example.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Examples_DoExample_FullMethodName = "/server.Examples/DoExample"
)

// ExamplesClient is the client API for Examples service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExamplesClient interface {
	DoExample(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type examplesClient struct {
	cc grpc.ClientConnInterface
}

func NewExamplesClient(cc grpc.ClientConnInterface) ExamplesClient {
	return &examplesClient{cc}
}

func (c *examplesClient) DoExample(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Examples_DoExample_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExamplesServer is the server API for Examples service.
// All implementations should embed UnimplementedExamplesServer
// for forward compatibility
type ExamplesServer interface {
	DoExample(context.Context, *Request) (*Response, error)
}

// UnimplementedExamplesServer should be embedded to have forward compatible implementations.
type UnimplementedExamplesServer struct {
}

func (UnimplementedExamplesServer) DoExample(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoExample not implemented")
}

// UnsafeExamplesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExamplesServer will
// result in compilation errors.
type UnsafeExamplesServer interface {
	mustEmbedUnimplementedExamplesServer()
}

func RegisterExamplesServer(s grpc.ServiceRegistrar, srv ExamplesServer) {
	s.RegisterService(&Examples_ServiceDesc, srv)
}

func _Examples_DoExample_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExamplesServer).DoExample(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Examples_DoExample_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExamplesServer).DoExample(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Examples_ServiceDesc is the grpc.ServiceDesc for Examples service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Examples_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server.Examples",
	HandlerType: (*ExamplesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoExample",
			Handler:    _Examples_DoExample_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/example.proto",
}
